### ISSUE TITLE
Error: Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by dustino** [mb3online/speck#37]
```
module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mb3-speck/dist/speck.js:33:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by ericadamski** [comment]
This is the issue! https://github.com/mb3online/speck/blob/develop/src/speck.js#L15
